### ISSUE TITLE
Improve example & suggestions

### ISSUE THREAD

**Issue by danbraik** [InvadingOctopus/comedot#1]
Hello,
thank you for this framework, I think it has a lot of potential.
I have played around and I have some suggestions to improve:
- it cannot be installed as an addon, I had to download the repo to make it work. Because the folder is named "Addons" instead of "addons", and the case is important is other systems than Windows. Moreover, the scripts were refering to "res://Entities" for exemple which is a folder outside the addon and won't be installed by user practice (or the day it is installed from the Godot Asset Library). Maybe this is an explicit intention to start with the full project ?
- I ran the exemple and there was a bug render. It seems that the tileset image source isn't in the repo, so the level rendering was invisible.
- I was expected to hurt ennemies with my bullets but it wasn't the case. It could be interesting to update the exemple with this behaviour to be kind of "complete" example. So I added a HealthComponent, DamageReceivingComponent but it wasn't working right away. I found after a long time of debugging that the collision mask should be configured. Also, funny thing, the Health component is updating the HUD label. So when the monster is hurt, it updates the HUD.
- I see that CollisionShapes for combat are already embedded in the component, so it is not configurable but I like the idea to have a default one if you know that every character is always one tile size and collision shape is not dynamic. When I was prototyping a component like that, I had an empty Area and let the user to instanciate its own CollisionShape under the component in the Entity scene. Maybe it could be a template the user can use with a DamaComponent and CollisionShape child.
- A suggestion about having an animation at death. I am sure how to implement it: it could be a DeathAnimationComponent listening to Health but when it is dead, it would still have Damage enabled or would be still targetable by AI bots... Or deleting the entity and spawning a temporary entity just to play death animation ?

Again, great work, I like the utility functions in Entity script and the quantity of available components!

**Comment by ShinryakuTako** [comment]
woo 1st issue! 

> it cannot be installed as an addon … the scripts were refering to "res://Entities" for exemple which is a folder outside the addon … Maybe this is an explicit intention to start with the full project ?

Yes, it's not a standalone add-on! I submitted it to the Godot Asset Library as a "Project Template". The first time you open the project, there will be many errors because the images etc. need to be imported first. Just close the project after Godot finishes scanning the files, and then reopen it.

> It seems that the tileset image source isn't in the repo

There is! Again just close the project and reopen it so the resources can get imported correctly.

> CollisionShapes for combat are already embedded … so it is not configurable

Right-Click on each Component node that you want to configure and enable "Editable Children" :) That will let you edit the shapes etc. for things like the DamageComponent.

The order of "ease of use" → "more power and control" goes like this:  
1. Use one of the templates from `res://Templates/`
2. Use the premade components and tweak their parameters in the Editor Inspector.
3. Enable **Editable Children** or **Make Local** to modify the subnodes of a component.
4. Make a subclass of a component's script, like `extends DamageComponent` and add your own features on top of the existing functionality.
5. Modify the original scripts to completely modify or replace the default functionality.

> A suggestion about having an animation at death.

Maybe I will add an "AnimationComponent" later. Right now you can make your own components like "MyPlayerComponent" or "MyMonsterComponent" which connect to the signals of other components, like `HealthComponent.healthDidZero`

**Comment by danbraik** [comment]
Hi, 
thank you for the answer! 
I like your order of usage, it make sense to enable "Editable Children". I think it may allow too to make update to the original component and having the update everywhere.
